version: "3.8"

services:
  api:
    build: .
    image: crypto-miner-backend:latest
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    ports:
      - "${API_PORT}:3000"

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    network_mode: "host"
    pid: "host"

volumes:
  data:
